'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApp5.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;pre&gt;
        '''&lt;font color=&quot;#5e6d03&quot;&gt;#include&lt;/font&gt; &lt;font color=&quot;#434f54&quot;&gt;&amp;lt;&lt;/font&gt;&lt;b&gt;&lt;font color=&quot;#d35400&quot;&gt;mcp_can&lt;/font&gt;&lt;/b&gt;&lt;font color=&quot;#434f54&quot;&gt;.&lt;/font&gt;&lt;font color=&quot;#000000&quot;&gt;h&lt;/font&gt;&lt;font color=&quot;#434f54&quot;&gt;&amp;gt;&lt;/font&gt;
        '''&lt;font color=&quot;#5e6d03&quot;&gt;#include&lt;/font&gt; &lt;font color=&quot;#434f54&quot;&gt;&amp;lt;&lt;/font&gt;&lt;b&gt;&lt;font color=&quot;#d35400&quot;&gt;mcp_can_dfs&lt;/font&gt;&lt;/b&gt;&lt;font color=&quot;#434f54&quot;&gt;.&lt;/font&gt;&lt;font color=&quot;#000000&quot;&gt;h&lt;/font&gt;&lt;font color=&quot;#434f54&quot;&gt;&amp;gt;&lt;/font&gt;
        '''&lt;font color=&quot;#5e6d03&quot;&gt;#include&lt;/font&gt; &lt;font color=&quot;#434f54&quot;&gt;&amp;lt;&lt;/font&gt;&lt;font color= [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property arducode() As String
            Get
                Return ResourceManager.GetString("arducode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_03_171510() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_03_171510", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_edit_clear_29769() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit-clear_29769", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_edit_clear_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit-clear_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_filter__add__16x16_9832() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_filter_(add)_16x16_9832", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_filter__add_b_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_filter_(add b)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_filter__add_id_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_filter_(add id)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_filter__delete__16x16_9833() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_filter_(delete)_16x16_9833", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_floppy_285657() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_floppy_285657", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_open_file_85334() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_open-file_85334", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_plug_green_68983() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_plug_green_68983", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_plug_red_69175() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_plug_red_69175", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_settings_115801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_settings_115801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_Sticky_12873() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_Sticky_12873", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBD2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBD2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
